# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ewma <- function(data, init, lambda) {
    .Call('_FHS_ewma', PACKAGE = 'FHS', data, init, lambda)
}

